name: shalat_schedule_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  hijriyah_indonesia: ^0.1.5
  http: ^1.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  sqflite: ^2.4.1
  stroke_text: ^1.0.0
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - data/HurufHijaiyah.json
    - data/AsmaulHusna.json
    - data/HukumTajwid.json
    - assets/splashscreen.png
    - assets/bgmenu.png
    - assets/ashar.png
    - assets/bgmenu.png
    - assets/dzuhur.png
    - assets/imsak.png
    - assets/isya.png
    - assets/subuh.png
    - assets/magrib.png
    - assets/kabah.png
    - assets/masjid.png
    - assets/al-Quran.png
    - assets/huruf-hijaiyah.png
    - assets/doa-harian.png
    - assets/asmaul-husna.png